name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable # the default is equivalent to `black . --diff --check`.
        with: # (optional - override the default params).
          args: [ ".", "--diff", "--line-length 120", "--check" ]
